In [ ]:
#sijisha paul_25070123138
# create dataset and load dataset

In [4]:
# dataset creation
import pandas as pd
data = {
      "roll no":[101,102,103,104,105],
      "gender":["female","male","female","male","female"],
      "department": ["computer","IT","ENTC","Mechanical","Computer"],
      "CGPA":[8.2,7.5,9.1,6.8,8.7]
 }

df=pd.DataFrame(data)

df.to_csv("student_data.csv", index=False)
df

   roll no  gender  department  CGPA
0      101  female    computer   8.2
1      102    male          IT   7.5
2      103  female        ENTC   9.1
3      104    male  Mechanical   6.8
4      105  female    Computer   8.7

In [5]:
df.shape

(5, 4)

In [6]:
df.size

20

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll no     5 non-null      int64
 1   gender      5 non-null      object
 2   department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [9]:
df.describe()

          roll no     CGPA
count    5.000000  5.00000
mean   103.000000  8.06000
std      1.581139  0.92358
min    101.000000  6.80000
25%    102.000000  7.50000
50%    103.000000  8.20000
75%    104.000000  8.70000
max    105.000000  9.10000

In [10]:
#upload the dataset
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [11]:
df.size

930

In [12]:
df.shape

(93, 10)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [14]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [15]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [16]:
df.sample(5)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
25,Dodge,Caravan,Van,19.0,17,Driver only,142,7,26.5,NaN
75,Pontiac,Grand_Prix,Midsize,18.5,19,NaN,200,5,28.5,16.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
69,Oldsmobile,Silhouette,Van,19.5,18,NaN,170,7,30.5,NaN
44,Hyundai,Elantra,Small,10.0,22,NaN,124,5,28.0,12.0

In [17]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [18]:
df.isnull().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.nunique()

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64